apiVersion: v1
kind: Namespace
metadata:
  name: my-isolated-ns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: my-isolated-ns
  name: wp-resource-quotas
spec: 
  hard: 
    cpu: 1000m
    memory: 512Mi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: my-isolated-ns
  name: wp-isolate-namespace
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: my-isolated-ns
  name: wp-configurations
data:
  dbHost: wp-mariadb-svc
  dbUser: wordpress
  dbName: wordpress
---
apiVersion: v1
kind: Secret
metadata:
  namespace: my-isolated-ns
  name: wp-secrets
type: Opaque
data:
  dbPassword: d29yZHByZXNz
  dbRootPassword: d29yZHByZXNz
