# frozen_string_literal: true
source "https://rubygems.org"

gem "jekyll", "~> 4.2"
gem "webrick", "~> 1.7"

group :jekyll_plugins do
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-feed", "~> 0.15.1"
  gem "jekyll-seo-tag", "~> 2.7"
end
